# Generated by Django 2.1.1 on 2018-09-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='氏名')),
                ('kana', models.CharField(max_length=16, verbose_name='かな')),
                ('position', models.CharField(max_length=8, null=True, verbose_name='役職')),
                ('department', models.CharField(max_length=16, verbose_name='部署')),
                ('mail', models.CharField(max_length=256, verbose_name='メールアドレス')),
                ('slack', models.CharField(max_length=256, verbose_name='Slack URL')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('seat_x', models.IntegerField(verbose_name='座席X座標')),
                ('seat_y', models.IntegerField(verbose_name='座席Y座標')),
                ('classification', models.CharField(max_length=16, verbose_name='雇用区分')),
            ],
            options={
                'db_table': 'talent',
            },
        ),
    ]
