# Generated by Django 2.1.1 on 2018-09-15 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='フロア名')),
                ('map', models.ImageField(upload_to='floors/', verbose_name='フロアマップ')),
            ],
            options={
                'db_table': 'floor',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='シート名')),
                ('x', models.IntegerField(verbose_name='X座標')),
                ('y', models.IntegerField(verbose_name='Y座標')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='talents.Floor', verbose_name='フロア')),
            ],
            options={
                'db_table': 'seat',
            },
        ),
        migrations.RemoveField(
            model_name='talent',
            name='seat_x',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='seat_y',
        ),
        migrations.AlterField(
            model_name='talent',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='seat',
            name='talent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='talents.Talent', verbose_name='タレント'),
        ),
    ]
