# Generated by Django 2.1.1 on 2018-09-16 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_auto_20180915_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='名称')),
                ('color', models.CharField(max_length=8, verbose_name='カラーコード')),
            ],
            options={
                'db_table': 'employment_status',
            },
        ),
        migrations.RemoveField(
            model_name='talent',
            name='classification',
        ),
        migrations.AlterField(
            model_name='seat',
            name='talent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='talents.Talent', verbose_name='タレント'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='position',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='役職'),
        ),
        migrations.AddField(
            model_name='talent',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talents', to='talents.EmploymentStatus', verbose_name='雇用形態'),
        ),
    ]
