# Generated by Django 2.1.1 on 2018-09-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0003_auto_20180916_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='パスワード'),
        ),
        migrations.AddField(
            model_name='talent',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='自己紹介文'),
        ),
    ]
