# Generated by Django 2.1.1 on 2018-10-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0004_auto_20180919_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='width',
            field=models.IntegerField(default=640, verbose_name='幅（ピクセル）'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='写真'),
        ),
    ]
