# Generated by Django 2.1.1 on 2018-10-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0006_talent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='business',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='業務内容'),
        ),
    ]
