# Generated by Django 2.1.1 on 2018-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0008_auto_20181118_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='mail',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='slack',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Slack URL'),
        ),
    ]
